SET SERVEROUTPUT ON FORMAT WRAPPED
SET TRIMSPOOL ON
SET PAGES 1000
SET LINES 500
WHENEVER SQLERROR EXIT FAILURE;
SPOOL ..\out\R_Suite_UTP
DECLARE
BEGIN

--  utResult.Ignore_Successes;

  utConfig.AutoCompile (FALSE);
  utPLSQL.Test ('COL_GROUP');

END;
/
SPOOL OFF
